export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import os from 'os'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h3>Contained id: {os.hostname()}</h3>
        {children}</body>
    </html>
  )
}