services:
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - db_bridge
      - web
  db:
    image: postgres:16.3-alpine3.20
    expose:
      - 5432:5432
    environment:
      - POSTGRES_USER=notes_db
      - POSTGRES_PASSWORD=0000
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - db_bridge

volumes:
  db-volume:


networks:
  db_bridge:
    driver: bridge
    internal: true
  web:
    driver: bridge
