services:
  django:
    build: main
    stop_signal: SIGKILL
    ports:
      - 127.0.0.1:8080:80
    extra_hosts:
    - "host.docker.internal:host-gateway"

  node:
    build: node
    ports:
    - 127.0.0.1:8081:80

  next:
    build: next
    ports:
    - 127.0.0.1:8082-8083:80
    deploy:
      mode: replicated
      replicas: 2


volumes:
  db-volume: