services:
  django:
    build: main
    stop_signal: SIGKILL
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:80

  node:
    build: node
    ports:
    - 127.0.0.1:8081:80

  next:
    build: next
    ports:
    - 127.0.0.1:8082:80

  db:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=notes_db
      - POSTGRES_PASSWORD=0000
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: