services:
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - django
      - node

  django:
    build: main
    stop_signal: SIGKILL
    depends_on:
      - db

  node:
    build: node

  db:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=notes_db
      - POSTGRES_PASSWORD=0000
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: