services:
  django:
    build: main
    stop_signal: SIGKILL
    network_mode: "host"

  node:
    build: node
    ports:
    - 127.0.0.1:8081:80

  next:
    build: next
    ports:
    - 127.0.0.1:8082-8083:80
    deploy:
      mode: replicated
      replicas: 2


volumes:
  db-volume: